<Project InitialTargets="ValidateGamePath">
  <Import Project="$(MSBuildThisFileDirectory)/GameFolder.props" Condition="Exists('$(MSBuildThisFileDirectory)/GameFolder.props')" />
  <Target Name="ValidateGamePath">
    <Error Text="The GameFolder property must be set to the GTFO game folder." Condition="'$(GameFolder)' == '' or !Exists('$(GameFolder)')" />
  </Target>

  <PropertyGroup>
    <BIELibsFolder>$(GameFolder)/BepInEx/core</BIELibsFolder>
    <DotNetFolder>$(GameFolder)/dotnet/</DotNetFolder>
    <InteropFolder>$(GameFolder)/BepInEx/interop</InteropFolder>
    <PluginLibFolder>$(GameFolder)/Plugins</PluginLibFolder>
    <pluginsFolder>$(GameFolder)/BepInEx/plugins</pluginsFolder>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(PluginLibFolder)/*.dll" Private="false" />
  </ItemGroup>

  <!-- BepInEx libs -->
  <ItemGroup>
    <Reference Include="$(BIELibsFolder)/BepInEx.*.dll" Private="false" />
    <Reference Include="$(BIELibsFolder)/0Harmony.dll" Private="false" />
    <Reference Include="$(BIELibsFolder)\MonoMod.RuntimeDetour.dll" Private="false" />
    <Reference Include="$(BIELibsFolder)\Il2CppInterop.*.dll" Private="false" />
  </ItemGroup>

  <!-- CorLibs -->
  <ItemGroup>
    <Reference Include="$(DotNetFolder)\*.dll" Private="false" />
    <Reference Include="$(DotNetFolder)/System.Private.CoreLib.dll" Private="false" />
  </ItemGroup>

  
  <!-- interop assemblies -->
  <ItemGroup>
    <Reference Include="$(InteropFolder)/*.dll" Private="false" />
    <!--<reference remove="$(interopfolder)/netstandard.dll" />
    <Reference Remove="$(InteropFolder)/Newtonsoft.Json.dll" />-->
  </ItemGroup>

  <!-- plugins folder -->
  <ItemGroup>
    <Reference Include="$(pluginsFolder)/MTFO.dll" Private="false" />
    <Reference Include="$(PluginsFolder)/GTFO-API.dll" Private="false" />
  </ItemGroup>


</Project>
