<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Platforms>AnyCPU;x64</Platforms>
      <AnalysisLevel>6.0-recommended</AnalysisLevel>
      <LangVersion>latest</LangVersion>
      <BaseOutputPath>I:\SteamLibrary\steamapps\common\GTFO\BepInEx\plugins</BaseOutputPath>
    </PropertyGroup>

    <Import Project="Dependencies.props" />

</Project>
